### ISSUE TITLE
Master-Detail Display

### ISSUE THREAD

**Issue by CSLiangNet** [NonFactors/MVC5.Grid#103]
HI,

I'm new with mvc and use this control,
I'm try to building Master-Detail Grid with MVC5.Grid in my project
for e.g. MasterGrid& DetailGrid
select MasterID to show Detail result

when DetailGrid show result, the Paging/Sorting function didn't work
but MasterGrid is fine

did I missing something?
or could u can provider some advice or sample?
thanks a lot.

sample code like this
html
```<div id='DetailDiv'>```

```JS
$('button:contains("CarNO")').on('click', function () {
            var CarID = this.dataset.id;
            var Time = this.value;            
            $.post(DetailUrl, {
                VehID: CarID,
                Time:Time
            }, function (htmlVal) {
               
                $("#DetailDiv").html(htmlVal)
            }
            );
        });
```

**Comment by Muchiachio** [comment]
You are not supposed to load the grid by yourself.
Please check [ajax grid](http://mvc-grid.azurewebsites.net/Grid/Ajax?mainParam=mainValue) and [grid reloading](http://mvc-grid.azurewebsites.net/Javascript/Reload) examples on how to use grid API, so it load the grid for you.

If you are still not sure how to do it, I would recommend you not using this grid and starting with a hand made tables. Once you get the hang of MVC framework you can add other frameworks into the mix, otherwise you will just confuse yourself with a lot of moving parts.

**Comment by CSLiangNet** [comment]
Hi,
thank u for link sample :+1:
