### ISSUE TITLE
CRUD default handlers mapped to Server Actions

### ISSUE THREAD

**Issue by papyr** [NonFactors/MVC5.Grid#104]
Hi, would it be possible to have CRUD actions support with the grid, so that they're mapped by default to Server Actions in a controller fluently when creating your ASP MVC grid.

This would simplify & speed up the use your MVC grid [similar to here](https://help.syncfusion.com/aspnetmvc/grid/data-adaptors)

By simply specifying the name of the Action fluently in Razor for each Create, Read, Update & delete the grid can handle passing this information there [sample code for the inner workings of the grid](https://github.com/syncfusion/JavaScript-Widgets/blob/master/Scripts/ej/web/ej.grid.min.js) and [here](https://github.com/telerik/kendo-ui-core/tree/master/docs-aspnet-mvc)

**Comment by Muchiachio** [comment]
Well yes, everything is theoretically possible, but it would add a whole new problem space to be supported.

And that's why I'm hesitant to even start working in that direction, because at the start people would want simple crud, later on they would want to add proper validations, callback handling, custom templates and so on.

Even looking at syncfunction, kendo or other full blown grids you can see that javascript file alone is at 10k+ lines, while `mvc-grid.js` is only at 838 currently. So would it really be worth it?

**Comment by papyr** [comment]
CRUD is such a basic and fundamental need.. sad to see it closed
