### ISSUE TITLE
Enum support

### ISSUE THREAD

**Issue by ThumNet** [NonFactors/MVC5.Grid#12]
Would it be possible to add Enum support to the Grid. Currently enums are displayed but are not filterable. I'd image filtering to be done using a dropdown box or something like that.

**Comment by Muchiachio** [comment]
Filtering enum is supported, but you need to implement your own filtering for that, because of varying enum definitions. As for general approach, I'm wondering how it would look like. Because adding server side filtering for enum is easy, but creating an intuitive client side filter is not. And I don't think that filtering by raw enum string or their number values would suffice. The only solution I can see know is to add some kind of attribute for declaring enumeration values, but that would add a lot of code to enumerations. What do you think?

**Comment by ThumNet** [comment]
For the cliënt side filter I was thinking about an extra attribute on the corresponding TH, this attribute is filled with  a json representation of the possible enum values.

For example:
public enum MyOptions : int {
   OptionA = 1,
   OptionB,
   OptionC
}

<th data-enum-options="{1:'OptionA', 2:'OptionB', 3:'OptionC'}">

Then the jquery filter would be that hard anymore :)

**Comment by ThumNet** [comment]
Part of the example was lost...

th data-enum-options="{1:'OptionA', 2:'OptionB', 3:'OptionC'}"

**Comment by Muchiachio** [comment]
Yes this can be done now too, but what would the values shown to the client be? Given enum
```C#
public enum MyOptions
{
    A,
    O,
    P
}
```
As a client I would not like to see raw enum values like A, O, P. I would like to see Apples, Pineapples, Oranges. We would need some kind of description attribute
```C#
public enum MyOptions
{
    [GridValue("Apples")] A,
    [GridValue("Oranges")] O,
    [GridValue("Pineapples")] P
}
```
But this solution, isn't really flexible to have, especially in localized scenarios.

**Comment by ThumNet** [comment]
I would use the existing Display Attribute
```
[Display(Name="Apples")]
````

But you are correct this isn't very flexible, there is a possible solution on [stackoverflow](http://stackoverflow.com/questions/17380900/enum-localization) that uses Resource files.

**Comment by Muchiachio** [comment]
I thought about it some more and decided to not do general enum support. Because:
- Using attributes to get proper display name is not very flexible and it adds a lot of code on bigger enums. Moreover it would not work on enums from 3rd party assemblies.
- Current [filter registration](https://github.com/NonFactors/MVC5.Grid/blob/develop/src/Mvc.Grid.Core/Filtering/IGridFilters.cs) implementation is very dependent on the type being filtered, like `Int32`, `String` and so on. Registering all enum types would require breaking this implementation pattern and go with something else.
- Loading all values from enum to th data tag or any other html tag doesn't really scale. Loading using ajax would require exposing the type name in the html and then loading the information from the controller.
- And other stuff, I don't remember by now...

Anyway, thanks for the suggestion :+1:

**Comment by ThumNet** [comment]
I totally understand your reasoning!

In my case I solved the issue by introducing a new Getter on the model which is the String presentation of the Enum. Then instead of displaying the enum I display the new getter in the grid, which in turn provides perfect filtering.
