### ISSUE TITLE
The specified type member 'Name' is not supported in LINQ to Entities

### ISSUE THREAD

**Issue by dragonsky18** [NonFactors/MVC5.Grid#13]
Hi,
    When I use AutoMapper， I  need to convert string to Uri that because automapper's projection don't support the converter , so I have to use projectusing as below according to automapper's documentation 
   Mapper.CreateMap<EFEntities.RelyingParties, Models.RelyingParty>() .ProjectUsing(source => new Models.RelyingParty { realm = new Uri(realm)});
   when running "Model.Rows.Count()" will throw exception 
The specified type member 'Name' is not supported in LINQ to Entities, 
I have tested , when I use formember,everything is ok ,but cannot use the projectusing.
 

Thanks in advance

**Comment by Muchiachio** [comment]
Grid doesn't do anything special with the query, if you are filtering name in your view, it will generate the same LINQ expression as written by hand. However mapping queries with AutoMapper can be tricky sometimes, but most of the time they can be fixed by inspecting generated query or replacing faulty properties. Try filtering out or running count on your created query in your controller and see if you don't get the exception.  
```C#
public ActionResult Index()
{
    var relyingParties = GetRelyingParties().AsQueryable();
    var parties = relyingParties.Where(party => party.Name == "Test").Count();
    var relyingPartiesList = relyingParties.Where(party => party.Name == "Test").ToList();

    return View(relyingParties);
}
```

**Comment by dragonsky18** [comment]
You are right，That's my fault。 
another thing ,I found the message " Obsoleting Project.To, creating all the overloads for ProjectTo" in automapper.
maybe you should modify your code in Select.cs
