### ISSUE TITLE
GridGlyphs.woff 404 in release mode.

### ISSUE THREAD

**Issue by ghost** [NonFactors/MVC5.Grid#132]
Hello,

I've encountered the following issue with the MVC5.Grid pack. All went well with installing and using it. However when publishing a website in **release** mode or testing a website in **release** mode, a 505 error occurs when the browser tries to get 
**GridGlyphs.woff** from the **/MvcGrid/Fonts/GridGlyphs.woff** path, to solve this I've changed
**src: url('../MvcGrid/Fonts/GridGlyphs.woff') format('woff');**

to src: **url('/Content/MvcGrid/Fonts/GridGlyphs.woff') format('woff');** I've found no other workaround for it. All mvc grid files have been added to a styles bundle as per the following code:
    **bundles.Add(new StyleBundle("~/Content/gridmvc").Include(
                      "~/Content/MvcGrid/mvc-grid.css"
                      ));**

Am I missing something ?

Thank you.

**Comment by Muchiachio** [comment]
Once you bundle your files these relative urls starts looking for font files from the new bundled file location, so it should be on the same level as mvc grid content. I'm not sure how to make this more reliable, so I just used what other using. I think that setting it to `/content/..` does not work with apps published under a non empty domain path, but I might be wrong.

**Comment by sunderedTomato** [comment]
I forgot to mention, I've tested this by publishing it to a testing web server, this is an MVC 5 project, I haven't tested the MVC6 grid library however. 
The browser usually points to http://address.testing.net/MvcGrid/Fonts/GridGlyphs.woff instead of http://address.testing.net/Content/MvcGrid/Fonts/GridGlyphs.woff . All other libraries are loading fine.

**Comment by Muchiachio** [comment]
Yes, because your bundle is probably included from `/Content/Bundle.css` and not from `/Content/AnyFolderName/Bundle.css`, so relative url doesn't work.

As for `/Content/MvcGrid/mvc-grid.css`, try deploying to root `address.testing.net/path/`, and your include will most likely fail too, because it will try to include `address.testing.net/Content/MvcGrid/mvc-grid.css`, that's why I'm suggesting using different bundle folder.
