### ISSUE TITLE
Installation is very poor

### ISSUE THREAD

**Issue by coinpennant** [NonFactors/MVC5.Grid#149]
Hi, I have follow

http://mvc-grid.azurewebsites.net/Home/Installation

but does not work. I want to use AjaxGrid. I have added $('.mvc-grid').mvcgrid(); but I still get
Uncaught TypeError: $(...).mvcgrid is not a function

I think some class "mvc-grid" is missing somewhere?

What about paging HTML, default grid HTML. How to configure it, etc

Documentation how to install and configure is very poor. I am still on jquery 2.x

**Comment by Muchiachio** [comment]
> but does not work. I want to use AjaxGrid. I have added $('.mvc-grid').mvcgrid(); but I still get
Uncaught TypeError: $(...).mvcgrid is not a function

Installation point 3 `Include grid scripts after jQuery scripts.`, that way `.mvcgrid` will be recognized.

> I think some class "mvc-grid" is missing somewhere?

Installation point 1 installs all the needed grid partials which contains `.mvc-grid` classes.
So rendering any grid with `@Html.Grid(Model)...` as shown in all [usage examples](http://mvc-grid.azurewebsites.net/) will render the html.

> What about paging HTML, default grid HTML. How to configure it, etc

Installation page only show how to configure the project, all the other pages contains the examples.

> Documentation how to install and configure is very poor. I am still on jquery 2.x

Not knowing the framework in which you are using the library doesn't mean that the library's documentation is poor.

**Comment by coinpennant** [comment]
I did exactly the same
"Installation point 3 Include grid scripts after jQuery scripts., that way .mvcgrid will be recognized."

I am using jquery2 and I have added grid scripts after it but I still get this errors

**Comment by Muchiachio** [comment]
Do you call `$('.mvc-grid').mvcgrid();` after jquery and grid scripts?

**Comment by juanrayner** [comment]
I have the same problem.
I followed the tutorial in the same way.
I am using asp.net core 2.1, NonFactors.Grid.Core.Mvc6 of NuGet and the references to the files I have downloaded GitHub and added manually, since this version does not bring them

**Comment by juanrayner** [comment]
I solved the error, I had installed NonFactors.Grid.Core.Mvc6 and manually added the references to the .chtml, .css and .js files downloaded from GitHub, because initially when I used NonFactors.Grid.Mvc6 the project did not solve the correct references to asp.net core 2.1.

But I deleted everything and added the version to NonFactors.Grid.Mvc6 again and it worked perfectly, of course following the installation steps of the [documentation](http://mvc6-grid.azurewebsites.net/Home/Installation).

Nothing but VS and its package versioning conflicts.

Good component, 100% recommended!

My only observation is that it would be good to be able to handle the text strings, externally in the case, such as my project, to work on internationalization.

**Comment by Muchiachio** [comment]
Grid already supports localization, did you find any strings which can't be changed?

**Comment by juanrayner** [comment]
Where can I find the documentation about the localization?

**Comment by juanrayner** [comment]
I have already found it, thanks

**Comment by Muchiachio** [comment]
On official [page](http://mvc6-grid.azurewebsites.net/Grid/Localization).
