### ISSUE TITLE
Reset page number & define param for Search 

### ISSUE THREAD

**Issue by boukenka** [NonFactors/MVC5.Grid#18]
[Research8.zip](https://github.com/NonFactors/MVC5.Grid/files/75628/Research8.zip)
Hello,

First a big thanks for your work. I have the following problems and questions:

A. How can I address to manage a search with @Html.AjaxGrid(Url.Action("IndexGrid",
    new { param = "value"}))? I mean how can I define the 'value' dynamically from an input on the web page? 

I have tried to add this value by doing the following:
reloadStarted: function (grid) {
 grid.sourceUrl = 'Home/IndexGrid/' + $('#searchString').val()

But it doesn't work when a change of page is done (from 1 to 2 for example). In that case, the reload event is not triggered. 

I have tried the 'gist' solution from the previous posts. But it doesn't work unfortunately 
(Grid.Query[Grid.Name + "-Search"]; is providing no value). 

Could you make a change in mvc-grid.cs to get the event when the paging is done? Or could you send me a solution where 'gist' is working (maybe I have done something wrong for the implementation)? 

B. How can I force after a refresh 'reload:true' to select the first page by default?

C. Do you plan to maintain the solution for mvc 5? Or any new feature/bug fixes will be only in MVC 6?

Thanks for your answers

PS: I have attached the project. It is not really perfect (I have just started to learn ASP.NETMVC 5 since 2 weeks)

**Comment by Muchiachio** [comment]
Hello,
@ddmactive, @zjean I include you too, as you may also be interested in actual example for this problem.

A) I made and [example on official page](http://mvc-grid.azurewebsites.net/Grid/GlobalSearch), on how to make ajax grid's global search, by filtering search input by hand. Check it out and see if it helps.
B) It's kind of ugly now, but you will need to reset grid query or it's parameters by hand, before each grid reload (the same principle as in global search example). I have a backlog item for making this and overall grid JS side extensibility easier for MVC5 v3.0 / MVC6 v1.0. v3.0 progress can be followed by checking out [MVC6.Grid commits](https://github.com/NonFactors/MVC6.Grid).
C) Yes MVC5 will be supported for quite a while, because I don't see MVC6 being ready for "normal" production usage until 2017~. And porting changes between the two is not hard.

**Comment by boukenka** [comment]
It is perfect. A and B could be solved. Thank you

**Comment by bradykelly** [comment]
Where is this `@Html.AjaxGrid` that I see in your examples? I find it nowhere in the NuGet package I used to install this grid. That method simple does not exist in the `NonFactors.Mvc.Grid` assembly.

**Comment by Muchiachio** [comment]
[Here](https://github.com/NonFactors/MVC5.Grid/blob/17084106f034e6a092b15a01600caa371fdadae4/src/Mvc.Grid.Core/Html/MvcGridExtensions.cs#L22), you need to include `NonFactors.Mvc.Grid` namespace in your page, if installation didn't include it in your `Web.config` namespaces.

**Comment by bradykelly** [comment]
Thank you very much. I don't know how I didn't see it in object browser yesterday, but I looked again, and there it was. The namespace was also present in the `web.config` for views. Today, suddenly, it is available in the page. Sorry about that, but I was getting desperate and it wasn't working.

**Comment by Muchiachio** [comment]
Sometimes restart/clean rebuild is needed for razor to catch newly added namespaces, so that could be it.
