### ISSUE TITLE
How to get DataSource (with checkbox column value) in mvc or jquery

### ISSUE THREAD

**Issue by agnihotriketan** [NonFactors/MVC5.Grid#25]
I want to save this grid data on formpost. Is there any way to post grid model with data in mvc using jquery or some other lib ? 

Thanks for your help in advance.
![issue](https://cloud.githubusercontent.com/assets/13862431/12410862/13a945f4-be9f-11e5-8a9e-32faf9f71455.png)

**Comment by Muchiachio** [comment]
You can just wrap your table in a form and post it's input values
```C#
<form>
    @Html.Grid(...)
</form>
```
Remember that you need to render actual `<input />`'s for it to work.

**Comment by agnihotriketan** [comment]
No, on form post I am not getting model back with checked values. It is null. Is there any way to get it in Jquery ? 



http://mvc-grid.azurewebsites.net/Home/Installation  this is helpful. can you add demo (like http://demos.telerik.com/kendo-ui/grid/index ) here as well so usage ll be quite smooth. I really appreciate your grid functioning. 

Cheers,
K10

**Comment by Muchiachio** [comment]
What do you mean by "not getting model back with checked values"? Did you add hidden or visible inputs to your grid for it to be posted back? I not so sure about adding this kind of example, because there are a lot of examples already, which cover the API, but adding unrelated examples would bloat the experience.
