### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ademgashi** [NonFactors/MVC5.Grid#27]
Hi, @Muchiachio I hope this messages finds you well with everything. I am using your grid and simply put I fell in love with it.

I think to make it perfect, where are some things that can be done and I am requesting them as features hoping that you will consider developing them.
Features that would make this library perfect according to my opinion are Column grouping, html helpers for rendering columns with images and buttons and bootstrap things.

Best Regards.

**Comment by Muchiachio** [comment]
Could you share an example of a simple table with grouping? I wanted to do something similar, but various sorting/filtering problems keep getting in the way.
I believe that any client side html, should be written by the client, because I will not be able to include every possible html out there. Even more so you can use your own or MVC helpers now, like
```C#
.Add(model => Html.CheckBoxFor(x => x.IsOk))
```
[Here's](https://github.com/NonFactors/MVC5.Template/blob/develop/src/MvcTemplate.Components/Extensions/Html/MvcGrid/MvcGridExtensions.cs) and actual example of how I make grid helpers, to avoid boilerplate code.

**Comment by ademgashi** [comment]
I totally agree that client code is not responsibility of the library, I just wanted so much that this library provides grouping. I agree that including other libraries will pollute you code and can loose the sense of it.
Anyway if you can look at this just to give you an idea http://www.jqwidgets.com/jquery-widgets-documentation/documentation/jqxgrid/jquery-grid-grouping.htm

**Comment by Muchiachio** [comment]
How would this work with paging/filtering/sorting?

**Comment by Muchiachio** [comment]
Closing as lost interest.
