### ISSUE TITLE
use HTML input types for Number and Date

### ISSUE THREAD

**Issue by Arithmomaniac** [NonFactors/MVC5.Grid#39]
Date filter should use `datetime-local`input type. Number filter should use `number` input type.
These both fall back to `text` if there is no browser support, so it should not be detrimental in any browser.

**Comment by Muchiachio** [comment]
You mean filters?

**Comment by Muchiachio** [comment]
There are few problems with those types.
- Number one usually blocks comma input (with default US browser settings), even though it may be valid on server side with different culture configuration or just thousand separator.
- Date time local, includes time which is not desired most of the time, I could consider using date if it doesn't bring more date formatting problems which are already present in current implementation.

**Comment by Arithmomaniac** [comment]
Hmmm... for Number, is it a real constraint to restrict people to their browser's own locale? I guess their browser could be set up incorrectly...
I use time sometime, but never realized it's required. I'd rather have the flexibility to be able to set it.

**Comment by Muchiachio** [comment]
Yes, I believe it's restricted to installed browser language. I'm using US version of the browser too, even though my native language is not English. And we all know that users will not change their locale, heck they don't even know it's possible. That's why I'm validating numbers, commas and dots by default now.

As for date, flexibility to set time would be great, but it's required now and I don't know about other browsers, but mine only gives date selection and then time needs to be set by hand or those arrows which takes a lot of time. I tried taking it's value without time through java script, but it returned empty value.

However, I do have plans to make some type of hints for filters. Like setting default filter type or value. So I'm thinking that it would be possible to do something about input types there. Maybe that way, we could differentiate between what's needed for particular case (date or datetime-local or number and so on).
