### ISSUE TITLE
Column Filter icon position is wrong when you use col-xs-2 on the column

### ISSUE THREAD

**Issue by Tazura** [NonFactors/MVC5.Grid#8]
Hi,

The filter icon of every column with the col-??-# style from bootstrap.
I reproduced it with your Quick Start view.

Here the code:
```C#
 @(Html
    .Grid(Model)
    .Build(columns =>
    {
		columns.Add(model => model.Name).Titled("Name").Css("col-xs-4");
		columns.Add(model => model.Surname).Titled("Surname").Css("col-xs-4");

		columns.Add(model => model.Age).Titled("Age").Css("col-xs-1");
		columns.Add(model => model.Birthday).Titled("Birth date").Css("col-xs-2");
		columns.Add(model => model.IsWorking).Titled("Employed").Css("col-xs-1");
    })
    .Filterable()
    .Sortable()
)
```
This used to work with the other mvc grid i was using, but I want to move to yours.

**Comment by Muchiachio** [comment]
This happens, because I'm using [relative positioning](https://github.com/NonFactors/MVC5.Grid/blob/develop/src/Mvc.Grid/Content/MvcGrid/mvc-grid.css#L13) to position the filter and bootstrap column overwrites it with `position: static;`. For now you can fix that by adding this selector to your style sheet.
```css
.mvc-grid-table .mvc-grid-header {
    position: relative;
}
```

I will check out other grids to see how they do it and will add a fix.

**Comment by Tazura** [comment]
Thanks it worked.

Adding this to the end of your css also work, so it could be the fix.
