### ISSUE TITLE
Issues with multiple Ajax grid

### ISSUE THREAD

**Issue by tonyuab** [NonFactors/MVC5.Grid#90]
I have multiple Ajax grid.  When doing paging on the bottom grid, the page always re-position to the top grid.  Any idea how to keep the screen at the same position if have mulitiple Ajax grid on the same screen?

**Comment by Muchiachio** [comment]
I think one of your grids is not ajax one, so it does a refresh and returns to the top of the page.

**Comment by tonyuab** [comment]
The view only have 3 nonfactor ajax grid.  the top 2 works as expected.  When the page button is clicked for the bottom grid, it does not return to the top of the page. It moved page up some (still shows the grid), but user has to scroll down in order to see the paging buttom.

**Comment by Muchiachio** [comment]
Could it be that rendering the new grid is taking some time, so that hiding the old one and rendering the new one resets the page scroll by a small margin? If so, you could try setting grid's container `min-height` to the current's content height on `reloadStarted` event and remove it on `reloadEnded`, maybe it will help.

**Comment by tonyuab** [comment]
that worked!  Thanks!
